/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.0.0
 *
 * Project: 'hello.Release+B-U585I-IOT02A' 
 * Target:  'Release+B-U585I-IOT02A' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* Keil::Device:STM32Cube HAL:Common:1.2.0 */
#define USE_HAL_DRIVER
/* Keil::Device:STM32Cube LL:Common:1.2.0 */
#define USE_FULL_LL_DRIVER


#endif /* PRE_INCLUDE_GLOBAL_H */
