/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.0.0
 *
 * Project: 'hello.Debug+B-U585I-IOT02A' 
 * Target:  'Debug+B-U585I-IOT02A' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32u5xx.h"

/* ARM::CMSIS-Compiler:I/O:STDOUT:User:1.0.0 */
#define RTE_Compiler_IO_STDOUT          /* Compiler I/O: STDOUT */
        #define RTE_Compiler_IO_STDOUT_User     /* Compiler I/O: STDOUT User */
/* ARM::CMSIS:RTOS2:Keil RTX5:Source:5.5.4 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
        #define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
        #define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
/* Keil::Device:STM32Cube Framework:STM32CubeMX:2.0.0 */
#define RTE_DEVICE_FRAMEWORK_CUBE_MX
/* Keil::Device:STM32Cube HAL:Common:1.2.0 */
#define RTE_DEVICE_HAL_COMMON
/* Keil::Device:STM32Cube HAL:Cortex:1.2.0 */
#define RTE_DEVICE_HAL_CORTEX
/* Keil::Device:STM32Cube HAL:DMA:1.2.0 */
#define RTE_DEVICE_HAL_DMA
/* Keil::Device:STM32Cube HAL:Flash:1.2.0 */
#define RTE_DEVICE_HAL_FLASH
/* Keil::Device:STM32Cube HAL:GPIO:1.2.0 */
#define RTE_DEVICE_HAL_GPIO
/* Keil::Device:STM32Cube HAL:I2C:1.2.0 */
#define RTE_DEVICE_HAL_I2C
/* Keil::Device:STM32Cube HAL:ICACHE:1.2.0 */
#define RTE_DEVICE_HAL_ICACHE
/* Keil::Device:STM32Cube HAL:MDF:1.2.0 */
#define RTE_DEVICE_HAL_MDF
/* Keil::Device:STM32Cube HAL:OSPI:1.2.0 */
#define RTE_DEVICE_HAL_OSPI
/* Keil::Device:STM32Cube HAL:PCD:1.2.0 */
#define RTE_DEVICE_HAL_PCD
/* Keil::Device:STM32Cube HAL:PWR:1.2.0 */
#define RTE_DEVICE_HAL_PWR
/* Keil::Device:STM32Cube HAL:RCC:1.2.0 */
#define RTE_DEVICE_HAL_RCC
/* Keil::Device:STM32Cube HAL:SPI:1.2.0 */
#define RTE_DEVICE_HAL_SPI
/* Keil::Device:STM32Cube HAL:UART:1.2.0 */
#define RTE_DEVICE_HAL_UART
/* Keil::Device:STM32Cube LL:Common:1.2.0 */
#define RTE_DEVICE_LL_COMMON
/* Keil::Device:STM32Cube LL:DLYB:1.2.0 */
#define RTE_DEVICE_LL_DLYB
/* Keil::Device:STM32Cube LL:GPIO:1.2.0 */
#define RTE_DEVICE_LL_GPIO
/* Keil::Device:STM32Cube LL:PWR:1.2.0 */
#define RTE_DEVICE_LL_PWR
/* Keil::Device:STM32Cube LL:RCC:1.2.0 */
#define RTE_DEVICE_LL_RCC
/* Keil::Device:STM32Cube LL:UCPD:1.2.0 */
#define RTE_DEVICE_LL_UCPD
/* Keil::Device:STM32Cube LL:UTILS:1.2.0 */
#define RTE_DEVICE_LL_UTILS
/* Keil::Device:Startup:Source C:1.0.0 */
#define RTE_DEVICE_STARTUP_STM32U5XX    /* Device Startup for STM32U5 */


#endif /* RTE_COMPONENTS_H */
